In [ ]:
from google.colab import files

uploaded = files.upload()

Saving netflix_titles.csv to netflix_titles.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("netflix_titles.csv")

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

director        29.908028
country          9.435676
cast             9.367549
date_added       0.113546
rating           0.045418
duration         0.034064
show_id          0.000000
type             0.000000
title            0.000000
release_year     0.000000
listed_in        0.000000
description      0.000000
dtype: float64

In [ ]:
df['director'] = df['director'].fillna('Unknown')

In [ ]:
df['cast'] = df['cast'].fillna('Unknown')

In [ ]:
df['country'] = df['country'].fillna('Unknown')

In [ ]:
df['rating'] = df['rating'].fillna('Unknown')

In [ ]:
df['date_added'] = df['date_added'].str.strip()

In [ ]:
df['date_added'] = pd.to_datetime(
    df['date_added'],
    errors='coerce'
)

In [ ]:
df['date_added'].isnull().sum()

np.int64(10)

In [ ]:
df['duration_value'] = df['duration'].str.extract(r'(\d+)')
df['duration_value'] = pd.to_numeric(df['duration_value'], errors='coerce')

In [ ]:
df['movie_duration_min'] = np.where(
    df['type'] == 'Movie',
    df['duration_value'],
    np.nan
)

In [ ]:
df['seasons'] = np.where(
    df['type'] == 'TV Show',
    df['duration_value'],
    np.nan
)

In [ ]:
df.drop(columns=['duration_value'], inplace=True)

In [ ]:
text_columns = [
    'type',
    'title',
    'director',
    'cast',
    'country',
    'rating',
    'listed_in',
    'description'
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['show_id'].duplicated().sum()

np.int64(0)

In [ ]:
df['release_year'].describe()

count    8807.000000
mean     2014.180198
std         8.819312
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

In [ ]:
df['release_year'].isnull().sum()

np.int64(0)

In [ ]:
df['year_added'] = df['date_added'].dt.year

In [ ]:
df['month_added'] = df['date_added'].dt.month

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   show_id             8807 non-null   object
 1   type                8807 non-null   object
 2   title               8807 non-null   object
 3   director            8807 non-null   object
 4   cast                8807 non-null   object
 5   country             8807 non-null   object
 6   date_added          8797 non-null   datetime64[ns]
 7   release_year        8807 non-null   int64
 8   rating              8807 non-null   object
 9   duration            8804 non-null   object
 10  listed_in           8807 non-null   object
 11  description         8807 non-null   object
 12  movie_duration_min  6128 non-null   float64
 13  seasons             2676 non-null   float64
 14  year_added          8797 non-null   float64
 15  month_added         8797 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(10)
memory usage: 1.1+ MB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   show_id             8807 non-null   object
 1   type                8807 non-null   object
 2   title               8807 non-null   object
 3   director            8807 non-null   object
 4   cast                8807 non-null   object
 5   country             8807 non-null   object
 6   date_added          8797 non-null   datetime64[ns]
 7   release_year        8807 non-null   int64
 8   rating              8807 non-null   object
 9   duration            8804 non-null   object
 10  listed_in           8807 non-null   object
 11  description         8807 non-null   object
 12  movie_duration_min  6128 non-null   float64
 13  seasons             2676 non-null   float64
 14  year_added          8797 non-null   float64
 15  month_added         8797 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(10)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

show_id                  0
type                     0
title                    0
director                 0
cast                     0
country                  0
date_added              10
release_year             0
rating                   0
duration                 3
listed_in                0
description              0
movie_duration_min    2679
seasons               6131
year_added              10
month_added             10
dtype: int64

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,movie_duration_min,seasons,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90.0,NaN,2021.0,9.0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN,2.0,2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",nan,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN,1.0,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,nan,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN,1.0,2021.0,9.0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN,2.0,2021.0,9.0

In [ ]:
df.shape

(8807, 16)

In [ ]:
df.to_csv(
    'netflix_cleaned.csv',
    index=False
)

In [ ]:
from google.colab import files

files.download('netflix_cleaned.csv')

In [35]:
# Split genres
df['listed_in'] = df['listed_in'].str.split(', ')

# Create one row for each genre
genre_df = df.explode('listed_in')

# Remove extra spaces
genre_df['listed_in'] = genre_df['listed_in'].str.strip()

# Save the file
genre_df.to_csv('netflix_genre_analysis.csv', index=False)

print(genre_df[['title', 'listed_in']].head(10))

                   title               listed_in
0   Dick Johnson Is Dead           Documentaries
1          Blood & Water  International TV Shows
1          Blood & Water               TV Dramas
1          Blood & Water            TV Mysteries
2              Ganglands          Crime TV Shows
2              Ganglands  International TV Shows
2              Ganglands   TV Action & Adventure
3  Jailbirds New Orleans              Docuseries
3  Jailbirds New Orleans              Reality TV
4           Kota Factory  International TV Shows

In [36]:
import os

os.path.exists('/content/netflix_genre_analysis.csv')

True

In [37]:
print(df.columns.tolist())

['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description', 'movie_duration_min', 'seasons', 'year_added', 'month_added']

In [38]:
# Make a copy
genre_df = df.copy()

# Split genres
genre_df['listed_in'] = genre_df['listed_in'].str.split(',')

# Put each genre into a separate row
genre_df = genre_df.explode('listed_in')

# Remove spaces
genre_df['listed_in'] = genre_df['listed_in'].str.strip()

# Check
print(genre_df[['title', 'listed_in']].head(20))

AttributeError: Can only use .str accessor with string values!

In [39]:
# Create a copy of the dataset
genre_df = df.copy()

# Convert listed_in to text and handle missing values
genre_df['listed_in'] = genre_df['listed_in'].fillna('').astype(str)

# Split genres by comma
genre_df['listed_in'] = genre_df['listed_in'].str.split(',')

# Create a separate row for each genre
genre_df = genre_df.explode('listed_in')

# Remove extra spaces
genre_df['listed_in'] = genre_df['listed_in'].str.strip()

# Remove empty genre values
genre_df = genre_df[genre_df['listed_in'] != '']

# Check the result
print(genre_df[['title', 'listed_in']].head(20))

                              title                     listed_in
0              Dick Johnson Is Dead             ['Documentaries']
1                     Blood & Water     ['International TV Shows'
1                     Blood & Water                   'TV Dramas'
1                     Blood & Water               'TV Mysteries']
2                         Ganglands             ['Crime TV Shows'
2                         Ganglands      'International TV Shows'
2                         Ganglands      'TV Action & Adventure']
3             Jailbirds New Orleans                 ['Docuseries'
3             Jailbirds New Orleans                 'Reality TV']
4                      Kota Factory     ['International TV Shows'
4                      Kota Factory           'Romantic TV Shows'
4                      Kota Factory                'TV Comedies']
5                     Midnight Mass                  ['TV Dramas'
5                     Midnight Mass                   'TV Horror'
5                     Midnight Mass               'TV Mysteries']
6  My Little Pony: A New Generation  ['Children & Family Movies']
7                           Sankofa                     ['Dramas'
7                           Sankofa          'Independent Movies'
7                           Sankofa       'International Movies']
8     The Great British Baking Show           ['British TV Shows'

In [40]:
# Remove brackets and quotes from genre names
genre_df['listed_in'] = (
    genre_df['listed_in']
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
    .str.replace("'", '', regex=False)
    .str.strip()
)

# Remove empty values
genre_df = genre_df[genre_df['listed_in'] != '']

# Check the result
print(genre_df[['title', 'listed_in']].head(20))

                              title                 listed_in
0              Dick Johnson Is Dead             Documentaries
1                     Blood & Water    International TV Shows
1                     Blood & Water                 TV Dramas
1                     Blood & Water              TV Mysteries
2                         Ganglands            Crime TV Shows
2                         Ganglands    International TV Shows
2                         Ganglands     TV Action & Adventure
3             Jailbirds New Orleans                Docuseries
3             Jailbirds New Orleans                Reality TV
4                      Kota Factory    International TV Shows
4                      Kota Factory         Romantic TV Shows
4                      Kota Factory               TV Comedies
5                     Midnight Mass                 TV Dramas
5                     Midnight Mass                 TV Horror
5                     Midnight Mass              TV Mysteries
6  My Little Pony: A New Generation  Children & Family Movies
7                           Sankofa                    Dramas
7                           Sankofa        Independent Movies
7                           Sankofa      International Movies
8     The Great British Baking Show          British TV Shows

In [41]:
genre_df.to_csv('/content/netflix_genre_analysis.csv', index=False)

print("✅ Genre analysis file created successfully!")

✅ Genre analysis file created successfully!